// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DataLayer.ResponseClasses.BSEEqtyMarketWatch", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("ATP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ask1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ask2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ask3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ask4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ask5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bids1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bids2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bids3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bids4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bids5")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("BuyPrice2")
                        .HasColumnType("REAL");

                    b.Property<double>("BuyPrice3")
                        .HasColumnType("REAL");

                    b.Property<double>("BuyPrice4")
                        .HasColumnType("REAL");

                    b.Property<double>("BuyPrice5")
                        .HasColumnType("REAL");

                    b.Property<int>("BuyQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyQty2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyQty3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyQty4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyQty5")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Change")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<string>("LastTrdTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<string>("MCapFF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MCapFull")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Market_Lot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OI")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentChange")
                        .HasColumnType("REAL");

                    b.Property<double>("PreCloseRate")
                        .HasColumnType("REAL");

                    b.Property<string>("PremTurnover")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("RBIRefRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rcount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScripName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SellPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("SellPrice2")
                        .HasColumnType("REAL");

                    b.Property<double>("SellPrice3")
                        .HasColumnType("REAL");

                    b.Property<double>("SellPrice4")
                        .HasColumnType("REAL");

                    b.Property<double>("SellPrice5")
                        .HasColumnType("REAL");

                    b.Property<int>("SellQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellQty2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellQty3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellQty4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellQty5")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TurnOver")
                        .HasColumnType("REAL");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UlaValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("W2AvgQ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wk52High")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wk52low")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("expDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lowerCircuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdPrice1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdPrice2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdPrice3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdPrice4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdPrice5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdQTy1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdQTy2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdQTy3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdQTy4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrdQTy5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrddttm1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrddttm2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrddttm3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrddttm4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mktTrddttm5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("strikePrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("upperCircuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("bSEEqtyMarketWatches");
                });

            modelBuilder.Entity("DataLayer.ResponseClasses.BSEScrips", b =>
                {
                    b.Property<string>("SCRIP_CD")
                        .HasColumnType("TEXT");

                    b.Property<string>("FACE_VALUE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GROUP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("INDUSTRY")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN_NUMBER")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mktcap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NSURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scrip_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("scrip_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SCRIP_CD");

                    b.ToTable("bseScrips");
                });
#pragma warning restore 612, 618
        }
    }
}
